In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
usda = pd.read_csv('../data/usda_expenditures.csv')
usda

,Year,Food at home expenditures million nominal U.S. dollars by households,Food at home expenditures million nominal U.S. dollars by government,Food at home expenditures million nominal U.S. dollars by home production,Food at home expenditures million constant 1988 U.S. dollars by households,Food at home expenditures million constant 1988 U.S. dollars by government,Food at home expenditures million constant 1988 U.S. dollars by home production,Food away from home expenditures million nominal U.S. dollars by households,Food away from home expenditures million nominal U.S. dollars by government,Food away from home expenditures million nominal U.S. dollars by home production,Food away from home expenditures million constant 1988 U.S. dollars by households,Food away from home expenditures million constant 1988 U.S. dollars by government,Food away from home expenditures million constant 1988 U.S. dollars by home production
0,1997,"351,807.63","23,677.15",842.93,"259,460.91","17,462.09",621.67,"265,068.59","16,615.44","54,711.66","205,639.20","12,890.19","42,445.10"
1,1998,"362,463.47","21,095.55",834.88,"262,341.63","15,268.41",604.26,"278,005.19","17,068.33","58,829.70","210,186.42","12,904.55","44,478.32"
2,1999,"384,929.53","20,066.85",812.49,"273,342.16","14,249.66",576.96,"292,034.97","17,662.16","62,424.47","215,444.33","13,029.99","46,052.70"
3,2000,"403,700.19","19,271.68",798.02,"280,354.06","13,383.43",554.19,"313,061.13","18,349.07","67,257.52","225,626.31","13,224.36","48,473.18"
4,2001,"422,530.75","20,155.39",786.39,"284,123.91","13,553.16",528.80,"326,063.38","19,058.11","68,519.59","228,375.63","13,348.35","47,991.30"
5,2002,"427,950.38","23,112.10",799.85,"284,162.94","15,346.64",531.11,"333,840.16","19,854.92","78,676.32","228,052.34","13,563.26","53,745.24"
6,2003,"443,745.44","26,462.25",810.46,"288,409.81","17,198.99",526.76,"354,630.19","20,550.26","80,801.38","237,199.09","13,745.31","54,045.07"
7,2004,"465,712.06","30,025.30",901.64,"291,632.81","18,802.10",564.61,"381,658.00","21,817.28","84,656.77","247,925.05","14,172.51","54,993.04"
8,2005,"490,800.75","34,036.84","1,223.36","301,514.03","20,909.88",751.55,"406,525.94","23,007.29","88,011.28","256,023.06","14,489.60","55,428.00"
9,2006,"514,023.72","35,643.70","1,394.85","310,384.06","21,522.81",842.25,"434,221.66","23,601.49","92,298.11","265,236.72","14,416.56","56,378.69"
10,2007,"542,098.69","36,132.39","1,032.90","314,088.34","20,934.87",598.45,"461,294.47","24,950.02","94,551.83","271,876.22","14,704.96","55,726.65"
11,2008,"563,130.25","41,202.43","1,103.36","306,647.91","22,436.44",600.83,"477,528.44","26,563.06","94,920.43","269,561.28","14,994.65","53,581.88"
12,2009,"536,072.19","57,558.10","1,055.28","290,558.09","31,197.24",571.98,"475,800.22","27,506.65","93,007.68","259,559.94","15,005.51","50,737.82"
13,2010,"537,142.56","72,124.71","1,153.22","290,177.81","38,963.57",623.00,"488,857.38","29,243.73","96,689.01","263,331.03","15,752.61","52,083.11"
14,2011,"561,723.31","79,650.34",871.82,"289,551.94","41,057.42",449.40,"517,050.00","30,876.39","104,814.55","272,153.94","16,252.06","55,170.09"
15,2012,"601,226.56","82,011.88",890.16,"302,462.81","41,258.23",447.82,"543,720.75","31,959.79","114,239.84","278,273.47","16,356.85","58,467.36"
16,2013,"613,336.38","83,403.84",977.43,"305,790.94","41,582.63",487.32,"576,383.56","33,313.70","120,577.08","288,822.56","16,693.30","60,420.50"
17,2014,"645,624.75","77,123.35","1,097.08","314,378.63","37,554.22",534.21,"619,000.13","34,668.95","130,029.27","302,811.13","16,959.84","63,609.54"
18,2015,"655,173.63","76,548.86","1,503.34","315,348.81","36,844.57",723.59,"675,332.75","35,914.76","141,250.14","321,183.91","17,080.83","67,177.66"
19,2016,"669,631.38","73,353.41","1,377.34","326,601.63","35,776.91",671.78,"717,941.31","37,291.14","151,150.95","332,877.50","17,290.24","70,081.98"
20,2017,"700,405.31","70,219.16","1,096.08","342,292.63","34,316.56",535.66,"768,070.00","38,154.82","158,455.61","347,998.06","17,287.23","71,793.26"
21,2018,"731,098.63","67,184.50","1,198.34","355,694.50","32,686.64",583.02,"815,998.06","39,200.26","158,561.73","360,243.19","17,305.96","70,001.13"
22,2019,"761,813.06","61,777.29","1,261.47","367,397.00","29,793.12",608.36,"845,048.00","40,301.13","177,971.89","361,896.00","17,259.16","76,217.35"
23,2020,"805,480.88","80,124.19","1,277.64","375,326.47","37,335.12",595.34,"760,042.19","36,790.55","134,833.63","314,934.63","15,244.71","55,870.29"
24,2021,"839,084.56","115,013.77","1,379.45","377,907.63","51,800.00",621.28,"913,619.94","45,582.80","201,885.38","362,122.91","18,067.22","80,019.40"
25,2022,"921,681.31","120,807.52","1,689.72","372,569.50","48,833.79",683.03,"1,052,251.13","55,404.66","228,058.86","387,411.31","20,398.55","83,965.30"
26,2023,"951,355.00","115,237.73","1,697.80","366,184.78","44,356.00",653.50,"1,199,372.50","49,940.06","254,163.78","412,367.25","17,170.35","87,386.38"

In [3]:
usda_filtered = usda[['Year', 
                  'Food at home expenditures million nominal U.S. dollars by households',
                  'Food away from home expenditures million nominal U.S. dollars by households']]
usda_filtered

,Year,Food at home expenditures million nominal U.S. dollars by households,Food away from home expenditures million nominal U.S. dollars by households
0,1997,"351,807.63","265,068.59"
1,1998,"362,463.47","278,005.19"
2,1999,"384,929.53","292,034.97"
3,2000,"403,700.19","313,061.13"
4,2001,"422,530.75","326,063.38"
5,2002,"427,950.38","333,840.16"
6,2003,"443,745.44","354,630.19"
7,2004,"465,712.06","381,658.00"
8,2005,"490,800.75","406,525.94"
9,2006,"514,023.72","434,221.66"
10,2007,"542,098.69","461,294.47"
11,2008,"563,130.25","477,528.44"
12,2009,"536,072.19","475,800.22"
13,2010,"537,142.56","488,857.38"
14,2011,"561,723.31","517,050.00"
15,2012,"601,226.56","543,720.75"
16,2013,"613,336.38","576,383.56"
17,2014,"645,624.75","619,000.13"
18,2015,"655,173.63","675,332.75"
19,2016,"669,631.38","717,941.31"
20,2017,"700,405.31","768,070.00"
21,2018,"731,098.63","815,998.06"
22,2019,"761,813.06","845,048.00"
23,2020,"805,480.88","760,042.19"
24,2021,"839,084.56","913,619.94"
25,2022,"921,681.31","1,052,251.13"
26,2023,"951,355.00","1,199,372.50"

In [4]:
usda_rename = usda_filtered.rename(columns={
    'Food at home expenditures million nominal U.S. dollars by households': 'Food At Home',
    'Food away from home expenditures million nominal U.S. dollars by households': 'Food Away From Home'
})
usda_rename

    Year Food At Home Food Away From Home
0   1997   351,807.63          265,068.59
1   1998   362,463.47          278,005.19
2   1999   384,929.53          292,034.97
3   2000   403,700.19          313,061.13
4   2001   422,530.75          326,063.38
5   2002   427,950.38          333,840.16
6   2003   443,745.44          354,630.19
7   2004   465,712.06          381,658.00
8   2005   490,800.75          406,525.94
9   2006   514,023.72          434,221.66
10  2007   542,098.69          461,294.47
11  2008   563,130.25          477,528.44
12  2009   536,072.19          475,800.22
13  2010   537,142.56          488,857.38
14  2011   561,723.31          517,050.00
15  2012   601,226.56          543,720.75
16  2013   613,336.38          576,383.56
17  2014   645,624.75          619,000.13
18  2015   655,173.63          675,332.75
19  2016   669,631.38          717,941.31
20  2017   700,405.31          768,070.00
21  2018   731,098.63          815,998.06
22  2019   761,813.06          845,048.00
23  2020   805,480.88          760,042.19
24  2021   839,084.56          913,619.94
25  2022   921,681.31        1,052,251.13
26  2023   951,355.00        1,199,372.50

In [5]:
households = pd.read_csv('../data/census_households.csv')
households

   Year Total Households
0  2019      122,802,852
1  2020      122,354,219
2  2021      127,544,730
3  2022      129,870,928
4  2023      131,332,360

In [6]:
merge_year = usda_rename.merge(households, on='Year')
merge_year.head(1)

   Year Food At Home Food Away From Home Total Households
0  2019   761,813.06          845,048.00      122,802,852

In [7]:
merge_year['Total Households'] = (
    merge_year['Total Households']
    .astype(str)
    .str.replace(',', '', regex=False)
    .astype(int)
)
merge_year.head(1)

   Year Food At Home Food Away From Home  Total Households
0  2019   761,813.06          845,048.00         122802852

In [8]:
merge_year['Food At Home'] = (
    merge_year['Food At Home']
    .astype(str)
    .str.replace(',', '', regex=False)
    .astype(float)
)

merge_year['Food Away From Home'] = (
    merge_year['Food Away From Home']
    .astype(str)
    .str.replace(',', '', regex=False)
    .astype(float)
)
merge_year.head(1)

   Year  Food At Home  Food Away From Home  Total Households
0  2019     761813.06             845048.0         122802852

In [9]:
merge_year['Per Household - Food At Home ($)'] = (merge_year['Food At Home'] * 1_000_000) / merge_year['Total Households']
merge_year['Per Household - Food Away From Home ($)'] = (merge_year['Food Away From Home'] * 1_000_000) / merge_year['Total Households']
merge_year

,Year,Food At Home,Food Away From Home,Total Households,Per Household - Food At Home ($),Per Household - Food Away From Home ($)
0,2019,761813.06,845048.00,122802852,6203.545338,6881.338554
1,2020,805480.88,760042.19,122354219,6583.188439,6211.818409
2,2021,839084.56,913619.94,127544730,6578.747393,7163.133592
3,2022,921681.31,1052251.13,129870928,7096.902472,8102.283908
4,2023,951355.00,1199372.50,131332360,7243.873483,9132.345600

In [10]:
merge_year['Per Household - Food At Home ($)'] = (
    merge_year['Food At Home'] * 1_000_000 / merge_year['Total Households']
)

merge_year['Per Household - Food Away From Home ($)'] = (
    merge_year['Food Away From Home'] * 1_000_000 / merge_year['Total Households']
)
merge_year.head(1)

,Year,Food At Home,Food Away From Home,Total Households,Per Household - Food At Home ($),Per Household - Food Away From Home ($)
0,2019,761813.06,845048.0,122802852,6203.545338,6881.338554

In [11]:
merge_year['Per Household - Food At Home ($)'] = merge_year['Per Household - Food At Home ($)'].round(2)
merge_year['Per Household - Food Away From Home ($)'] = merge_year['Per Household - Food Away From Home ($)'].round(2)
merge_year.head(1)

,Year,Food At Home,Food Away From Home,Total Households,Per Household - Food At Home ($),Per Household - Food Away From Home ($)
0,2019,761813.06,845048.0,122802852,6203.55,6881.34

In [12]:
merge_year.iloc[:, 1:] = merge_year.iloc[:, 1:].applymap(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)
merge_year.head()

C:\Users\user\AppData\Local\Temp\ipykernel_17096\3491066305.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  merge_year.iloc[:, 1:] = merge_year.iloc[:, 1:].applymap(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)
C:\Users\user\AppData\Local\Temp\ipykernel_17096\3491066305.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0    761,813.06
1    805,480.88
2    839,084.56
3    921,681.31
4    951,355.00
Name: Food At Home, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  merge_year.iloc[:, 1:] = merge_year.iloc[:, 1:].applymap(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)
C:\Users\user\AppData\Local\Temp\ipykernel_17096\3491066305.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0      845,048.00
1      760,042.19
2      913,619.94
3    1,052,251.13
4    1,199,372.50
Name: Food Away From Home, dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  merge_year.iloc[:, 1:] = merge_year.iloc[:, 1:].applymap(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)
C:\Users\user\AppData\Local\Temp\ipykernel_17096\3491066305.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0    122,802,852.00
1    122,354,219.00
2    127,544,730.00
3    129,870,928.00
4    131,332,360.00
Name: Total Households, dtype: object' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  merge_year.iloc[:, 1:] = merge_year.iloc[:, 1:].applymap(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)
C:\Users\user\AppData\Local\Temp\ipykernel_17096\3491066305.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0    6,203.55
1    6,583.19
2    6,578.75
3    7,096.90
4    7,243.87
Name: Per Household - Food At Home ($), dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  merge_year.iloc[:, 1:] = merge_year.iloc[:, 1:].applymap(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)
C:\Users\user\AppData\Local\Temp\ipykernel_17096\3491066305.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0    6,881.34
1    6,211.82
2    7,163.13
3    8,102.28
4    9,132.35
Name: Per Household - Food Away From Home ($), dtype: object' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  merge_year.iloc[:, 1:] = merge_year.iloc[:, 1:].applymap(lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) else x)

,Year,Food At Home,Food Away From Home,Total Households,Per Household - Food At Home ($),Per Household - Food Away From Home ($)
0,2019,"761,813.06","845,048.00","122,802,852.00","6,203.55","6,881.34"
1,2020,"805,480.88","760,042.19","122,354,219.00","6,583.19","6,211.82"
2,2021,"839,084.56","913,619.94","127,544,730.00","6,578.75","7,163.13"
3,2022,"921,681.31","1,052,251.13","129,870,928.00","7,096.90","8,102.28"
4,2023,"951,355.00","1,199,372.50","131,332,360.00","7,243.87","9,132.35"

In [7]:
plt.figure(figsize=(10, 6))
plt.fill_between(merge_year['Year'], merge_year['Per Household - Food At Home ($)'], color='Green', label = 'Green Line', alpha=0.6, label='Food At Home')
plt.fill_between(merge_year['Year'], merge_year['Per Household - Food Away From Home ($)'], color='Light Green', label = 'Light Green Line', alpha=0.6, label='Food Away From Home')
plt.title('Area Chart of Per Household Food Spending: At Home vs Away (2019-2023)', fontsize=16)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Per Household Spending ($)', fontsize=12)
plt.legend(title="Spending Category")
plt.xticks(ticks=merge_year['Year'], labels=[int(year) for year in merge_year['Year']])
plt.show()

NameError: name 'plt' is not defined